config/routes.rb
Passwordlet::Application.routes.draw do
  root :to => "homes#index"
  
  devise_for :users
  
  get "bookmarklet" => "bookmarklet#show"
  get "bookmarklet/signed_in" => "bookmarklet#signed_in"

  resources :domains do
    collection do
      get "login"
    end    
  end
end

app/models/domain.rb
require 'openssl'

class Domain < ActiveRecord::Base
  attr_reader :password
  attr_accessible :name, :domain_url, :domain_username, :password, :user_id
  validates :name, :domain_url, :domain_username, :domain_password, :user_id, :presence => true
  
  belongs_to :user

  def password=(password)
    @password = password
    self.domain_password = encrypt(password)
  end

  def password
    decrypt(self.domain_password)
  end

  def get_cookies(url, username, password)
    agent = Mechanize.new
    agent.user_agent_alias = 'Mac Safari'
    agent.follow_meta_refresh = true

    unless url[/\Ahttp:\/\//] || self.domain_url[/\Ahttps:\/\//]
      url = "http://#{url}"
    end

    page = agent.get(url)

    page.forms.each do |form|
      if form.field_with(:type => "password")
        if form.field_with(:type => "text")
          form.field_with(:type => "text").value = username
        else
          form.field_with(:type => "email").value = username
        end
        form.field_with(:type => "password").value = password
        form.submit
      end
    end

    cookies = {}
    agent.cookies.each do |cookie|
      c = {}
      c["name"] = cookie.name
      c["value"] = cookie.value
      c["domain"] = cookie.domain
      c["secure"] = cookie.secure
      c["expires"] = cookie.expires.to_s
      c["path"] = cookie.path.to_s
      cookies[cookie.name] = c
    end

    cookies
  end

  private

  def encrypt(plain_data)
    cipher = OpenSSL::Cipher::Cipher.new('aes-256-cbc')
    cipher.encrypt
    cipher.key = ENV["AES_KEY"]
    cipher.iv = ENV["IV"]
    encrypted = cipher.update(plain_data)
    encrypted << cipher.final
    Base64.encode64(encrypted).encode('utf-8')
  end

  def decrypt(encrypted_data)
    cipher = OpenSSL::Cipher::Cipher.new('aes-256-cbc')
    cipher.decrypt
    cipher.key = ENV["AES_KEY"]
    cipher.iv = ENV["IV"]
    decoded_data = Base64.decode64(encrypted_data.encode('ascii-8bit'))
    decrypted = cipher.update(decoded_data)
    decrypted << cipher.final
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :domains, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # OJOJOOJO: Rober: I have commented this line which is provided by default with rails and added all code below in order to 
  # add CSRF protection 
  #protect_from_forgery with: :exception

  protect_from_forgery

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers, :set_csrf_cookie_for_ng

# For all responses in this controller, return the CORS access control headers.

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    headers['Access-Control-Max-Age'] = "1728000"
  end

# If this is a preflight OPTIONS request, then short-circuit the
# request, return only the necessary headers and return an empty
# text/plain.

  def cors_preflight_check
    if request.method == :options
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
      headers['Access-Control-Request-Method'] = '*'
      headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
      headers['Access-Control-Max-Age'] = '1728000'
      render :text => '', :content_type => 'text/plain'
    end
  end

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

protected

  def verified_request?
    super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
  end  
end

app/controllers/bookmarklet_controller.rb
class BookmarkletController < ApplicationController
  
  def show
    render :show, :formats => :js
  end 

  def signed_in
    if user_signed_in?
      render :json => {"message" => "signed in"}, :callback => params['callback']
    else
      render :json => {"message" => "not signed in"}, :callback => params['callback']
    end
  end

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    if user_signed_in?
      @domains = Domain.where(:user_id => current_user.id)
    end
    render :json => @domains
  end

  def new
    @domain = Domain.new
    render :new  
  end

  def create
    @domain = Domain.new(params[:domain])
    @domain.domain_url = URI.parse(params[:domain][:domain_url]).to_s
    @domain.user_id = current_user.id
    
    if @domain.save
      render :json => @domain
    else
      render :json => @domain.errors.full_messages
    end    
  end

  def login
    @domain = Domain.where('user_id = ? AND domain_url LIKE ?', current_user.id, '%' + params[:domain] + '%').first

    if @domain
      @cookies = @domain.get_cookies(@domain.domain_url, @domain.domain_username, @domain.password)
      render :json => @cookies.to_json, :callback => params['callback']
    else
      render :json => {"message" => "domain not found"}, :callback => params['callback']
    end
  end

  def update
    @domain = Domain.find(params[:id])
    @domain.update_attributes(params[:domain])
    render :json => @domain
  end

  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy
    render :json => { "message" => "domain deleted" }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarklet_helper.rb
module BookmarkletHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def index
    render :index
  end
end

app/views/bookmarklet/show.js.erb
(function(e,a,g,h,f,c,b,d){if(!(f=e.jQuery)||g>f.fn.jquery||h(f)){c=a.createElement("script");c.type="text/javascript";c.src="https://ajax.googleapis.com/ajax/libs/jquery/"+g+"/jquery.min.js";c.onload=c.onreadystatechange=function(){if(!b&&(!(d=this.readyState)||d=="loaded"||d=="complete")){h((f=e.jQuery).noConflict(1),b=1);f(c).remove()}};a.getElementsByTagName("head")[0].appendChild(c)}})(window,document,"1.3.2",function($,L){

  showOverlay("Connecting to Passwordlet..");

  $.ajax({
    type: "GET",
    url: "https://gentle-taiga-4945.herokuapp.com/bookmarklet/signed_in",
    dataType: "jsonp",
    async: false,
    contentType: "application/json",
    success: function(data) {
      if (data.message == "not signed in") {
        hideOverlay();
        showOverlay("Please log in to Passwordlet.");
        setTimeout(function() {
          showPasswordlet("https://gentle-taiga-4945.herokuapp.com/users/sign_in");
          hideOverlay();
        }, 1000);
      } else {
        $.ajax({
          type: "GET",
          url: "https://gentle-taiga-4945.herokuapp.com/domains/login",
          data: { domain: location.hostname },
          dataType: "jsonp",
          async: false,
          contentType: "application/json",
          success: function(data) {
            hideOverlay();

            if (data.message == "domain not found") {
              showOverlay("This domain is not registered in Passwordlet.");
              setTimeout(function() {
                showPasswordlet("https://gentle-taiga-4945.herokuapp.com/#domains/new");
              }, 1000);
            } else {
              setCookie(data);
              window.location.reload();
              showOverlay("You are good to go!");
              setTimeout(function(){
                $(".overlay").remove();
              }, 2000);
            }
          },
          error: function(data) {
            showOverlay("Oops, something went wrong.");
          }
        });
      }
    }
  });

  function setCookie(cookies) {
    for(var cookie in cookies) {
      var cookieStr = "";
      cookieStr += cookies[cookie].name + "=" + cookies[cookie].value + "; ";
      cookieStr += "expires=" + cookies[cookie].expires + "; ";
      cookieStr += "domain=" + cookies[cookie].domain + "; ";
      cookieStr += "path=" + cookies[cookie].path + ";";
      document.cookie = cookieStr;
    }
  }

  function showPasswordlet(url) {
    window.open(url, 'Passwordlet', 'width=600, height=600, left=100, top=100').focus();
  }

  function hideOverlay() {
    $(".overlay").remove();
  }

  function showOverlay(message) {
    var overlay = $("<div class='overlay'></div>").css({
      width: "100%",
      height: $(document).height(),
      position: "absolute",
      left: 0,
      top: 0,
      display: "none",
      backgroundColor: "#333",
      opacity: 0.9,
      zIndex:10000000
    });

    var closeButton = $("<div class='close'></div>").css({
      width: "30px",
      height: "30px",
      position: "absolute",
      top: "30px",
      right: "30px",
      opacity: 0.8,
      backgroundImage: 'url("https://gentle-taiga-4945.herokuapp.com/assets/close.png")',
      backgroundPosition: 0
    });

    $(overlay).prepend(closeButton);

    if (typeof message != 'undefined') {
      var overlayText = $("<div>" + message + "</div>").css({
        margin: "30px 50px",
        color: "#fff",
        fontSize: "24px",
        fontWeight: "100",
        fontFamily: "Helvetica Neue, Arial, sans-serif",
        zIndex:10000001
      });
      $(overlay).prepend(overlayText);
    }

    $("body").prepend(overlay);
    $(".overlay").fadeIn(200);

    $(".close").mouseenter(function(){
      $(this).css({
        opacity: 1,
        cursor: "pointer"
      });
    }).mouseleave(function(){
      $(this).css({
        opacity: 0.8
      });
    });

    $(".close").click(function(){
      $(".overlay").remove();
    });
  }

});

app/views/domains/index.html.erb
<div class="domains section">
  <ul>
  <% @domains.each do |domain| %>
    <li>
    <%= domain.name %><br>
    <%= domain.domain_url %><br>
    <%= domain.domain_username %><br>
    <%= domain.domain_password %><br>
    <%= button_to "Log me in!!", login_domain_url(domain), :method => :get %>
    </li>
  <% end %>
  </ul>
</div>

app/views/domains/new.html.erb
<div class="section">
  <h1>New Domain</h1>
  <%= form_for @domain do |f| %>
  <div class="row">
    <%= f.label(:name, "Domain name") %>
    <%= f.text_field(:name, :placeholder => "Domain name") %>
  </div>
  <div class="row">
    <%= f.label(:domain_url, "Domain URL") %>
    <%= f.text_field(:domain_url, :placeholder => "http://") %>
  </div>
  <div class="row">
    <%= f.label(:domain_username, "Username") %>
    <%= f.text_field(:domain_username, :placeholder => "Your username for this domain") %>
  </div>
  <div class="row">
    <%= f.label(:password, "Password") %>
    <%= f.password_field(:password, :placeholder => "Your password for this domain") %>
  </div>
  <br>
    <%= f.submit("Add domain") %>
  <% end %>
</div>

app/views/homes/index.html.erb
<div class="content">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passwordlet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1 class="title">Passwordlet</h1>
  <div class="nav">
    <a href="http://twitter.com/kyungmink" target="_blank">Feedback</a>
    <div style="display: inline-block; width: 16px;"></div>
    <% if current_user %>
      <%= link_to "Sign out", destroy_user_session_url, {:method => :delete} %>
    <% else %>
      <%= link_to "Sign in", new_user_session_url %> <span class="divider">
    <% end %>
  </div>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <% if alert.is_a?(Array) %>
      <% alert.each do |alert_item| %>
        <p class="alert"><%= alert_item %></p>
      <% end %>
    <% else %>
      <p class="alert"><%= alert %></p>
    <% end %>  
  <% end %>
    <%= yield %>
  <div class="footer">
    Made by <a href="http://kyungm.in">Kyungmin Kim</a> © 2013. Powered by Heroku.
  </div>
</body>
<script type="text/data" id="current-user-id"><%= current_user.id if user_signed_in? %></script>
<script type="text/javascript">
  if (document.location.pathname == "/") {
    $("h1.title").hide();
  } else {
    $("h1.title").show();
  }
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45768423-1', 'passwordlet.com');
  ga('send', 'pageview');

</script>
</html>